### PR TITLE
Milestone 1: Hello Microverse

### PR DESCRIPTION
**Pull request by kimitaWanjohi**
- Added a Hello Microverse h1 header
- Added text color to the header

### CODE REVIEW

**Review by topeogunleye — CHANGES_REQUESTED** [review]
Hi @kimitaWanjohi, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

Try-Again

> ## (Highlights) Good Points: 💪 
> * Good commit messages. :heavy_check_mark:
> * Followed Github flow :heavy_check_mark:

## Required Changes ♻️
- [x] Kindly add linters to your project. In the root project, you need to have a folder named .github. Inside this one, you need another folder named workflows. And inside the workflows folder, you need a file named linters.yml. Inside this file, you need to have the linters. The linters needed for this project can be found [here](https://github.com/microverseinc/linters-config/tree/master/html-css);
>Here is a video demo I created demostrating  the above:
>
https://user-images.githubusercontent.com/52934128/164221056-46f41b39-cb1e-4fd9-a7f9-dd47bf835439.mp4
- [x] Kindly ensure your linter results pass * AKA: Linter should report NO errors.

- [x] In the case of README consider not leaving any of the sections in the [Microverse README](https://github.com/microverseinc/readme-template) template as it's a project requirement.

| professional Readme  | Your Readme that is not professional |
| ------------- | ------------- |
|  Recording 2023-02-14 at 12 52 20 (5)	  | kimitaWanjohi_Hello-Microverse at html-header and 46 more pages - Personal - Microsoft_ Edge 2023-02-14 15-58-08  |

- [x] please kindly add a more descriptive PR title and description as seen in the demo below:
pull_request_desc

- [x] Kindly create a `.gitignore` file, then add `test.md` and `node_modules` to your .gitgignore file as node_modules can be added by accident while setting up Linters
Here is a video demo of the above:

https://user-images.githubusercontent.com/52934128/164221760-0a8ce8da-7bb5-471c-9746-7c4e1cc6c99c.mp4

 You used the correct GitHub flow, but the branch should have the name of a feature or action (e.g. 'created_sidebar' or 'added_comments_section'). Kindly rename 'html-header' following [this article](https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/managing-branches-in-your-repository/renaming-a-branch) or checkout to a new branch and use the correct name and mention the old PR in the new PR.

- [x] Kindly add and commit a `.html` and `.css` file to your branch directory

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
- Nothing to mention.

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag @topeogunleye in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by kimitaWanjohi** [comment]
- Added a Hello Microverse h1 header
- Added text color to the header

**Review by mahbubul14 — CHANGES_REQUESTED** [review]
Hi @kimitaWanjohi,

Great work on making the changes requested by the previous reviewer 👏

You've done well implementing some of the requested changes, but there are still some which aren't been addressed yet.

# Required Changes ♻️

- [ ] Pull Request should have a descriptive title telling you what changes are inside and a short summary describing introduced changes in more detail. Kindly work on it.
Pr

###  To Highlights
:heavy_check_mark: No linter error.
:heavy_check_mark: Proper Github flow used.

### Optional suggestions

Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better.

* N/A

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification. You can also reach me on [slack](https://microverse-students.slack.com/team/U01J39GL614)

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
```

**Review by KanzaTahreem — APPROVED** [review]
# Approved 🥳

Hi @kimitaWanjohi 👋

Great work implementing the changes suggested by reviewers. I would like to express my deep appreciation for the time and effort you dedicated to this project 💪 I wish you success 🥇

**_Your project is COMPLETE! There is nothing else to say other than... it's time to merge it! 🚀 Congratulations!_**



## Highlights 🎯
There are some excellent points that you have made perfectly. Keep up the great work! 👏

-  ✅ Your PR have a descriptive title, perfect!
-  ✅ Great work using the right GitHub Flow 
-  ✅ Your README looks professional, well done!
-  ✅ Linters are working properly, great job! 

## Optional suggestions ❕
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👨‍💻💻

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Pull request merged**
